version: "3.7"

services:
  django:
    build:
      context: .
    command: ./manage.py runserver 0.0.0.0:8000
    env_file: .env.dev
    environment:
      DATABASE_URL: postgres://django:password@postgres:5432/mysite
      EMAIL_URL: smtp://mailhog:1025
      CACHE_URL: memcache://memcached:11211
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - mailhog
      - memcached
    volumes:
      - .:/code

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mysite

  memcached:
    image: memcached

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
