FROM python:3.8-slim

# Install our dependencies
RUN apt-get update && apt-get install -y build-essential libpq-dev

WORKDIR /code/
COPY . /code/

RUN pip install -r requirements.txt

CMD ["gunicorn", "-b", "0.0.0.0:8000", "mysite.wsgi:application"]

EXPOSE 8000
