FROM python:3.8-slim

# Install gunicorn as well as Django
RUN pip install Django==3.0.2 django-environ==0.4.5 gunicorn==20.0.4

WORKDIR /code/
COPY . /code/

# Run gunicorn rather than ./manage.py runserver
CMD ["gunicorn", "-b", "0.0.0.0:8000","mysite.wsgi:application"]

EXPOSE 8000
